[package]
name = "filcrypto"
description = "FFI Interface to Filecoin Proofs"
version = "0.7.5"
authors = [
  "nemo <nemo@protocol.ai>",
  "dignifiedquire <me@dignifiedquire.com>",
  "laser <l@s3r.com>"
]
license = "MIT OR Apache-2.0"
repository = "https://github.com/filecoin-project/filecoin-ffi"
readme = "README.md"
edition = "2018"
publish = false

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
bls-signatures = { version = "0.7.1", default-features = false, features = ["blst"] }
blstrs = { version = "0.1.3" }
byteorder = "1.2"
drop_struct_macro_derive = "0.4.0"
ff = { version = "0.2.1", package = "fff" }
ffi-toolkit = "0.4.0"
groupy = "0.3.0"
libc = "0.2.58"
log = "0.4.7"
fil_logger = "0.1.0"
rand = "0.7"
rand_chacha = "0.2.1"
rayon = "1.2.1"
anyhow = "1.0.23"
#bellperson = { version = "0.12.0", default-features = false, features = ["gpu"] }
bellperson = { path = "../../bellperson", features = ["gpu"] }
serde_json = "1.0.46"
rust-gpu-tools = "0.2.0"

[dependencies.filecoin-proofs-api]
package = "filecoin-proofs-api"
#version = "5.4.1"
path = "../../rust-filecoin-proofs-api"
default-features = false

[build-dependencies]
cbindgen = "= 0.14.0"

[dev-dependencies]
tempfile = "3.0.8"

[features]
default = ["pairing"]
pairing = ["filecoin-proofs-api/pairing", "bellperson/pairing"]
blst = ["filecoin-proofs-api/blst", "bellperson/blst"]
blst-portable = ["bls-signatures/blst-portable", "blstrs/portable"]
